#!/bin/bash
exec 3>/dev/null
__bigPointer(){
	echo -e "\033[34;1m==>\033[0m $1" 1>&2
}

if [ "$1" != "resume" ]
then
__bigPointer "Cleaning..."
rm .processed
for dir in $(ls -1)
do
	pushd $dir >/dev/null
	hmake distclean |& awk '{print "\t"$0;}'
	popd >/dev/null
done
fi
for dir in $(ls -1)
do
	grep -q "$dir" .processed && continue
	pushd $dir >/dev/null
	__bigPointer "Building $dir"
	(hmake build || echo >> ../.fuckedup) |& awk '{print "\t"$0;}' && echo "$dir" >> ../.processed 
	popd >/dev/null
done
__bigPointer "Collecting repository..."
rm -rf repo
mkdir repo
cp */*.hard repo
__bigPointer "Collected $(ls -1 repo | wc -l) packages"
__bigPointer "Writing entries to ROADMAP..."
pushd repo >/dev/null
for package in $(ls -1)
do
	echo "${package%.hard}:${package}:" >> ROADMAP
done
popd >/dev/null
__bigPointer "Written $(cat repo/ROADMAP | wc -l) entries"
__bigPointer "Now you can add package descriptions manually"

