#!/bin/bash  

##    This file is part of hpkg.

##    hpkg is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.

##    hpkg is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.

##    You should have received a copy of the GNU General Public License
##    along with hpkg.  If not, see <https://www.gnu.org/licenses/>.

exec 3>/dev/null

__cderror(){
	echo "cd error"
	exit 1
}
__build(){
if [ -z "$1" ]; then
	__cderror
fi

cd "$1" 2>&3 || __cderror

if ! [ -e "Buildfile" ]; then
	echo "NO Buildfile"
	exit 1
fi

if grep -q "withpasswd" Buildfile ; then
	CRYPT="passwd"
elif grep -q "withkey" Buildfile ; then
	CRYPT="key"
else
	__cderror
fi

PACKAGE=$(grep "Package: " Buildfile | sed 's/Package: //')
ARCH=$(grep "Type: " Buildfile | sed 's/Type: //')
ACCESS=$(grep "Access: " Buildfile | sed 's/Access: //')
VER=$(grep "Version: " Buildfile | sed 's/Version: //')
WORKNAME="HPKG_PAYLOAD"
echo "$ARCH" > .ARCH_TYPE
echo "$ACCESS" > .ACCESS 
echo "$PACKAGE" > .PKGNAME
if ! [ -z "$VER" ]; then
echo "$VER" > .VERSION
cd "PAYLOAD" 2>&3 || __cderror
tar cvf "../PAYLOAD.tar" . || __cderror
cd ..
rm -rf "PAYLOAD"
fi
cd ..
cp -r "$1" "$WORKNAME"
tar cvf "$WORKNAME".tar "$WORKNAME"
tar -f "$WORKNAME".tar --delete "$WORKNAME/Buildfile"
xz -9 "$WORKNAME".tar
if [ "$CRYPT" == "passwd" ] ; then
	gpg --batch --yes --passphrase $REALPASS -c "$WORKNAME".tar.xz
elif [ "$CRYPT" == "key" ] ; then
	gpg -es "$WORKNAME".tar.xz
fi 
rm -rf "$WORKNAME" "$WORKNAME".tar.xz
mv "$WORKNAME".tar.xz.gpg "$1".hard
}
