#!/bin/bash

#DEBUG=YES

. /usr/lib/hpkglib.sh

CONFIGUREOPTS="--prefix=/usr --sysconfdir=/etc"
MAINTAINER="$(whoami)@$(hostname)"

. /etc/hpkg/make.conf

#[[ "$UID" == 0 ]] || error "$_root_or_fakeroot" "32" 

FD1="1"
exec 5>"${DISTDIR}/hpkg-make.log"

is_true "$DEBUG" || FD1="5"

__getsrc()	{	true;	}
__unpacksrc()	{	true;	}
__preparesrc()	{	true;	}
__compilesrc()	{	true;	}
__installsrc()	{	false;	}

usage(){
printf "\
$(i18n "hpkg-make - create .hard package")\n\
\n\
$(i18n "hpkg-make <command>")\n\
\n\
$(i18n "Commands"):\n\
  build			$(i18n "Read Buildfile and build package")\n\
  pack $(i18n "<directory>")	$(i18n "Create package from given directory")\n\
  clean			$(i18n "Clean build and destination directories")\n\
  build_clean		$(i18n "Like 'clean' but keep destination directory")\n\
  mrproper		$(i18n "Completely purge everyrhing related to package")\n\
  install		$(i18n "Install built package")\n\
\n\
$(i18n "More information available at hpkg-make(1) manpage")\n\
$(i18n "Copyright and licensing information can be obtained via '--version' option")\n"
exit 0
}

strip_result(){
	local save_lib="ld* libc* libpthread* libthread_db*"
	pushd $DEST/lib
		for LIB in $save_lib; do
			objcopy --only-keep-debug $LIB $LIB.dbg
			strip --strip-unneeded $LIB
			objcopy --add-gnu-debuglink=$LIB.dbg $LIB
		done
	popd
	local save_usr_lib="libquadmath* libstdc++* libitm* libatomic*"
	pushd $DEST/usr/lib
		for LIB in $save_usr_lib; do
			objcopy --only-keep-debug $LIB $LIB.dbg
			strip --strip-unneeded $LIB
			objcopy --add-gnu-debuglink=$LIB.dbg $LIB
		done
	popd
	unset LIB save_lib save_usr_lib
	find $DEST/usr/lib $DEST/lib -type f -name "*.a" \
		-exec strip --strip-debug {} ';'
	find $DEST/usr/lib $DEST/lib -type f -name "*.so*" ! -name "*dbg" \
		-exec strip --strip-unneeded {} ';'
	find $DEST/{bin,sbin} $DEST/usr/{bin,sbin,libexec} -type f \
		-exec strip --strip-all {} ';'
	find $DEST/ -type f -name "*.la" \
		-delete
}

pack(){
	pushd $PACKAGEDIR
		echo "#!/bin/bash"			>> METADATA
		echo "PKGNAME=\"$PACKAGE\""		>> METADATA
		echo "VERSION=\"$VER\""			>> METADATA
		echo "DESCRIPTION=\"$DESCRIPTION\""	>> METADATA
		echo "MAINTAINER=\"$MAINTAINER\""	>> METADATA
		echo "DEPENDS=(${DEPENDS[@]})"		>> METADATA
		echo "CONFLICTS=(${CONFLICTS[@]})"	>> METADATA
		echo "PROVIDES=(${PROVIDES[@]})"	>> METADATA
		type pkg_preinstall 	|& sed '1d'	>> METADATA
		type pkg_postinstall 	|& sed '1d'	>> METADATA
		type pkg_preremove	|& sed '1d'	>> METADATA
		type pkg_postremove	|& sed '1d'	>> METADATA
		
		tar cv --numeric-owner --owner=0 --group=0 -f $PACKAGE.hard METADATA
		tar --append -f $PACKAGE.hard PAYLOAD.tar.zst

		gpg -s $PACKAGE.hard
		mv $PACKAGE.hard.gpg ${PACKAGE}_${VER}.hard

		rm PAYLOAD.tar.zst
	popd &>/dev/null
}

build(){
	. ./Buildfile || error "$(i18n "Cannot read Buildfile")" "32"
	{ [[ -z "$PACKAGE" ]] || \
	  [[ -z "$VER" ]]; } && error "$(i18n "Invalid Buildfile")" "32"
	declare -xf __installsrc __compilesrc strip_result error pointer warn is_true i18n
	PACKAGEDIR="$DISTDIR/$PACKAGE"
	DEST="$PACKAGEDIR/root"
	BUILDDIR="$PACKAGEDIR/build"
	export DISTDIR PACKAGE PACKAGEDIR DEST BUILDDIR MAKEOPTS FD1 FD2 SRCDIR CONFIGUREOPTS POINTERCOLOR WARNCOLOR CLRCOLOR
	mkdir -p $DEST $BUILDDIR
	pushd $BUILDDIR &>/dev/null
	pointer "$(i18n "Running getsrc()")..."
	__getsrc 1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to get sources")" "1"
	pointer "$(i18n "Running unpacksrc()")..." 
	__unpacksrc 1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to unpack sources")" "1"
	pushd $SRCDIR &>/dev/null
	pointer "$(i18n "Running preparesrc()")..."
	__preparesrc 1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to prepare sources")" "1"
	popd &>/dev/null
	popd &>/dev/null
	pointer "$(i18n "Entering chroot environment")..."
	fakeroot /bin/bash <<EOF
	pushd $BUILDDIR &>/dev/null
	pushd $SRCDIR	&>/dev/null
	pointer "$(i18n "Running compilesrc()")"
	__compilesrc 1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to compile sources")" "1"
	pointer "$(i18n "Running installsrc()")..."
	__installsrc 	1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to install into package")" "1"
	pointer "$(i18n "Stripping")..." 
	strip_result 	1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to strip")" "1"
	popd 		&>/dev/null
	popd 		&>/dev/null
	pointer "$(i18n "Creating package")..."
	pushd $DEST 	&>/dev/null
		tar cvp -I "zstd -10" -f $PACKAGEDIR/PAYLOAD.tar.zst . 1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to create package")" "1"
	popd 		&>/dev/null
EOF
	pointer "$(i18n "Leaving chroot environment")..."
	pointer "$(i18n "Signing package")..."
	pack 		1>&${FD1} 2>&${FD1} || error "$(i18n "Failed to create package")" "1"
}

clean(){
	. ./Buildfile || error "$(i18n "Can not read Buildfile")" "32"
	PACKAGEDIR="$DISTDIR/$PACKAGE"
	DEST="$PACKAGEDIR/root"
	BUILDDIR="$PACKAGEDIR/build"
	rm -rf $BUILDDIR
	rm -rf $DEST
}

build_clean(){
	. ./Buildfile || error "$(i18n "Can not read Buildfile")" "32"
	PACKAGEDIR="$DISTDIR/$PACKAGE"
	DEST="$PACKAGEDIR/root"
	BUILDDIR="$PACKAGEDIR/build"
	rm -rf $BUILDDIR
}

mrproper(){
	. ./Buildfile || error "$(i18n "Can not read Buildfile")" "32"
	PACKAGEDIR="$DISTDIR/$PACKAGE"
	DEST="$PACKAGEDIR/root"
	BUILDDIR="$PACKAGEDIR/build"
	rm -rf $PACKAGEDIR
}

[[ -z "$*" ]] && usage
{ [[ "$1" == "--help" ]] || [[ "$1" == "--usage" ]]; } && usage
[[ "$1" == "--version" ]] && version


case $1 in 
	build)	build;;
	pack)
		cd $2
		{
			. ./METADATA || error "$(i18n "Can not read METADATA")" "32"
			tar cvf "package.tar" METADATA
			cd root
			tar cvpJf ../PAYLOAD.tar.xz .
			cd ..
			tar --append -f package.tar PAYLOAD.tar.xz
			gpg -s package.tar
			mv package.tar.gpg ../${PKGNAME}_${VER}.hard
		} >&${FD1}
		cd ..
		exit 0;;
	install)
		. ./Buildfile || error "$(i18n "Can not read Buildfile")" "32"
		hpkg -p $DISTDIR/$PKGNAME/*_*.hard || error "$(i18n "Can not install package")" "1";;
	clean) 		clean;;
	build_clean) 	build_clean;;
	mrproper) 	mrproper;;
esac

