#!/bin/bash

##    This file is part of hpkg.

##    hpkg is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.

##    hpkg is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.

##    You should have received a copy of the GNU General Public License
##    along with hpkg.  If not, see <https://www.gnu.org/licenses/>.

__scan(){
	STUB="$1.hard.stub"
	echo -e "# hmake instruction list \n# generated with hscan by $(whoami)@$(hostname) on $(LC_ALL="C" date)" > $STUB
	[ -e ./bootstrap ] && echo -e "NEED_BOOTSTRAP\nAUTOTOOLS" >> $STUB
	[ -e ./autogen ] && echo -e "NEED_AUTOGEN\nAUTOTOOLS" >> $STUB
	[ -e ./configure ] && echo -e "AUTOTOOLS" >> $STUB

	# TODO 
	# Cmake support and smth

	[ -z "$2" ] || echo "URL: $2" >> $STUB
	echo "-^:^^^:---|  DEPENDS  |---:^^^:^-" >> $STUB
	echo "Please enumerate dependencies (1 per line; ^C to stop)"
	trap "break" SIGINT
	while true
	do
		read -p "> " DEP
		echo $DEP >> $STUB
	done
	echo "-^:^^^:---|  CONFLICTS  |---:^^^:^-" >> $STUB
	echo "Please enumerate conflicts (1 per line; ^C to stop)"
	while true
	do
		read -p "> " CONF
		echo $CONF >> $STUB
	done

} 

case $1 in
	--local)
			[ -z $2 ] && echo "Usage $0 $1 package_name" && exit 1
			__scan "$2"
		;;
	--git)
			[ -z $2 ] && echo "Usage $0 $1 remote/repo.git package_name" && exit 1
			[ -z $3 ] && echo "Usage $0 $1 remote/repo.git package_name" && exit 1
			PREV=$(pwd)
			TEMP=$(mktemp -d)
			git clone $2 $TEMP || exit 1
			cd $TEMP || exit 1
			__scan "$3" "$2"
			mv $STUB $PREV/
		;;
	*)
		echo "Usage: --local || --git "
		;;
esac