install:
	@mkdir -p $(DESTDIR)/var/hardman/modules/enabled
	@echo "  INSTALL     default-install"
	@install default-install ${DESTDIR}/var/hardman/modules/default-install
	@echo "  INSTALL     default-resolve"	
	@install default-resolve ${DESTDIR}/var/hardman/modules/default-resolve
	@echo "  INSTALL     default-download"	
	@install default-download ${DESTDIR}/var/hardman/modules/default-download
	@echo "  INSTALL     default-update-db"
	@install default-update-db $(DESTDIR)/var/hardman/modules/default-update-db
	@echo "  INSTALL     default-lowlevel"
	@install default-lowlevel ${DESTDIR}/var/hardman/modules/default-lowlevel
