name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get libaria2
      run: sudo apt-get install libaria2-0-dev
    - name: Get gettext
      run: sudo apt-get install gettext
    - name: Get libhrd
      run: |
        git clone https://github.com/EmptiedSoul/hrdlib.git
        cd hrdlib/src
        make
        sudo make install
        cd ../..
    - name: configure
      run: ./configure
    - name: make
      run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
